name: Percy VR
on: [pull_request, workflow_dispatch]

jobs:
  vr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Run Percy
        run: |
          yarn
          yarn server_percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
